#!/bin/bash

if [ -f .PIDServer ]; then
    echo ":PIDServer file found. Please kill first before rerun"
    exit 1
fi
redisTest="$(redis-cli ping)"
expected="PONG"
if [ "$redisTest" != "$expected" ]
then
	echo "Please run redis before starting the server"
	exit 1
fi


celery -A noriv2apiserver worker -l info > logs/celery 2>&1 &
echo $! > .PIDServer
./wsserver.py > logs/wsserver 2>&1 &
echo $! >> .PIDServer
./manage.py runserver | tail logs/django &
echo $! >> .PIDServer
