#!/bin/bash
redisTest="$(redis-cli ping)"
expected="PONG"
if [ "$redisTest" != "$expected" ]
then
	echo "Please run redis before starting the server"
	exit 0
fi


celery -A noriv2apiserver worker -l info > logs/celery 2>&1 &
echo $! > .PIDServer
./wsserver.py > logs/wsserver 2>&1 &
echo $! >> .PIDServer
./manage.py runserver > logs/django 2>&1 &
echo $! >> .PIDServer
