#!/bin/bash

if [ ! -f .PIDServer ]; then
    echo ":PIDServer file not found. Server maybe not running?"
    exit 0
fi

while IFS='' read -r line || [[ -n "$line" ]]; do
	if ps -p $line > /dev/null
	then    
		kill $line
	fi
done < ".PIDServer"

rm .PIDServer
