#!/bin/bash

if [ ! -f .PIDServer ]; then
    echo ":PIDServer file not found. Server maybe not running?"
    exit 1
fi

while IFS='' read -r line || [[ -n "$line" ]]; do
	if ps -p $line > /dev/null
	then
		kill $line
	fi
done < ".PIDServer"

rm .PIDServer

# In my Arch it doesn't kill manage.py properly (two processes spawn, only one is being killed):

pkill -f "/usr/bin/python3 ./manage.py runserver"

